### ISSUE TITLE
Project currently wont compile.

### ISSUE THREAD

**Issue by DraxCodes** [DraxCodes/Youtube2Mp3#1]
This issue is due to the fact that the current implementation to get the users playlist doesn't seem to allow us to access the list of tracks. 

ℹ️ If we have to use the depricated method to fix this for now, we may as-well do that.

**Comment by DraxCodes** [comment]
Making this a question/discusion. Let me know any further ideas you have for it 😄

**Comment by svr333** [comment]
The only compile error I found was a wrong implementation of the interface.

**Comment by svr333** [comment]
@DraxCodes, when using the GetUserPlaylists() method, it's a Paging<SimplePlaylist>.
SimplePlaylist contains a Tracks property, however, the Tracks only cover `href` & `TotalTracks`.
There is no way to actually get information about the tracks. I'm pretty sure we **have** to use the deprecated method.

**Comment by DraxCodes** [comment]
Fixed
